### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by JasperBleijenberg** [calbertsen/multi_SAM#5]
Hi, 

trying to install the package thows an error: 

make: *** [C:/Users/xxxx/AppData/Local/Programs/R/R-42~1.2/etc/x64/Makeconf:260: multiStockassessment.o] Error 1
ERROR: compilation failed for package 'multiStockassessment'

I try to run on Windows 10 with 
R 4.2.2
> packageVersion('stockassessment')
[1] ‘0.12.0’
> packageVersion('TMB')
[1] ‘1.9.4’
> packageVersion('RcppEigen')
[1] ‘0.3.3.9.3’
> packageVersion('Rcpp')
[1] ‘1.0.10’

Error 1 also turns up when runnning on Linux Ubuntu 20.04 with the following setup:
R 4.3.1
> packageVersion('stockassessment')
[1] ‘0.12.0’
> packageVersion('TMB')
[1] ‘1.9.4’
> packageVersion('RcppEigen')
[1] ‘0.3.3.9.3’
> packageVersion('Rcpp')
[1] ‘1.0.10’

Could you provide some help to overcome the problem? 

Kind regards, Jasper

**Comment by calbertsen** [comment]
You can install the development version from r-universe.dev. Note that the `stockassessment` package must be a specific version for everything to work:

```r
install.packages('stockassessment', repos = c('https://calbertsen.r-universe.dev', 'https://cloud.r-project.org'))
install.packages('multiStockassessment', repos = c('https://calbertsen.r-universe.dev', 'https://cloud.r-project.org'))
```

**Comment by JasperBleijenberg** [comment]
thanks, that did the trick
